### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by komasoftware** [manolo/gwt-polymer-chat-app#1]
I'd love to try this but can't get it to build :

koen@desktop:~/src/gwt-polymer-chat-app$ mvn gwt:compile 
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.gwtconf:gwt-polymer-chat:war:1.2.1.0-alpha1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-resources-plugin is missing. @ line 100, column 21
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:gwt-maven-plugin is missing. @ line 68, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building GWT Polymer Chat 1.2.1.0-alpha1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.google.gwt:gwt-user:jar:2.8.0.VC-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.google.gwt:gwt-codeserver:jar:2.8.0.VC-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.vaadin.polymer:vaadin-gwt-polymer-elements:jar:1.2.1.0-alpha1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.251 s
[INFO] Finished at: 2015-11-21T17:57:25+01:00
[INFO] Final Memory: 15M/481M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gwt-polymer-chat: Could not resolve dependencies for project org.gwtconf:gwt-polymer-chat:war:1.2.1.0-alpha1-SNAPSHOT: Failed to collect dependencies at com.googlecode.gwtquery:gwtquery:jar:1.4.4-SNAPSHOT -> com.google.gwt:gwt-elemental:jar:2.8.0-SNAPSHOT: Failed to read artifact descriptor for com.google.gwt:gwt-elemental:jar:2.8.0-SNAPSHOT: Failure to find com.google.jsinterop:jsinterop:pom:1.0.0-SNAPSHOT in http://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by manolo** [comment]
Could you try if it compiles for you now?

Thanks

**Comment by komasoftware** [comment]
Still having issues :
Could not find artifact com.google.jsinterop:jsinterop:pom:1.0.0-SNAPSHOT

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.528 s
[INFO] Finished at: 2015-11-22T10:34:23+01:00
[INFO] Final Memory: 11M/481M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gwt-polymer-chat: Could not resolve dependencies for project org.gwtconf:gwt-polymer-chat:war:1.2.1.1-SNAPSHOT: Failed to collect dependencies at com.googlecode.gwtquery:gwtquery:jar:1.4.4-SNAPSHOT -> com.google.gwt:gwt-elemental:jar:2.8.0-SNAPSHOT: Failed to read artifact descriptor for com.google.gwt:gwt-elemental:jar:2.8.0-SNAPSHOT: Could not find artifact com.google.jsinterop:jsinterop:pom:1.0.0-SNAPSHOT in sonatype-snapshots (http://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

**Comment by manolo** [comment]
have you checked out the project? it should look for 2.8.0.VC-SNAPTHOT latest gwt 2.0.8-SNAPSHOT is broken

https://github.com/manolo/gwt-polymer-chat-app/blob/master/pom.xml#L14

**Comment by manolo** [comment]
You are right, there were transitive dependencies using broken gwt-2.8.0-SNAPSHOT.
Please, try again

**Comment by komasoftware** [comment]
Great ! Thx a lot.

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:40 min
[INFO] Finished at: 2015-11-22T11:55:41+01:00
[INFO] Final Memory: 16M/481M
[INFO] ------------------------------------------------------------------------
